# Required Python packages:
#
# ansible
# openstackclient
# openstacksdk

- import_playbook: common.yaml

- hosts: all
  gather_facts: no

  tasks:
  # - name: 'Remove the Control Plane servers'
  #   os_server:
  #     name: "{{ item.1 }}-{{ item.0 }}"
  #     state: absent
  #   with_indexed_items: "{{ [os_cp_server_name] * os_cp_nodes_number }}"

  - name: 'Remove the Control Plane servers'
    os_server:
      name: "{{ cluster_name }}-{{ node_type }}-{{ hostname }}"
      state: absent
    loop: "{{ masters }}"
    loop_control:
      loop_var: node
      label: "{{ fqdn }}"
    vars:
      node_type: "master"
      hostname: "{{ node['name'] }}"
      ip_cluster: "{{ node['ip_cluster'] }}"
      fqdn: "{{ node['name'] }}.{{ cluster_domain }}"
    register: ports

  - name: 'Remove the Control Plane server group'
    os_server_group:
      name: "{{ os_cp_server_group_name }}"
      state: absent
