# Required Python packages:
#
# ansible
# openstackclient
# openstacksdk

- import_playbook: common.yaml

- hosts: all
  gather_facts: no

  tasks:
  - name: 'List security groups'
    ansible.builtin.shell: openstack security group list -f json | jq '.[] | select(.Name | test("{{ cluster_name | string }}")) | .ID'
    register: security_groups

  - name: 'Remove the cluster security groups'
    command:
      cmd: "openstack security group delete {{ item.1 }}"
    with_indexed_items: "{{ security_groups.stdout_lines }}"
