- hosts: all
  gather_facts: no

  tasks:

    - name: Run openshift-install steps for a fresh install
      block:
        - name: Ensure {{ cluster_domain }} dir exists
          file:
            path: "../scripts/{{ cluster_domain }}"
            state: directory

        - name: Generate install-config.yaml
          template:
            src: install-config.yaml.j2
            dest: "../scripts/{{ cluster_domain }}/install-config.yaml"

        - name: Backup install-config.yaml
          copy:
            src: "../scripts/{{ cluster_domain }}/install-config.yaml"
            dest: "../scripts/install-config.yaml.bkp"

        - name: Generate manifests
          command: openshift-install create manifests --dir=../scripts/{{ cluster_domain }}
