kind: Pod
apiVersion: v1
metadata:
  name: mdns-publisher
  namespace: openshift-kni-infra
  creationTimestamp:
  deletionGracePeriodSeconds: 65
  labels:
    app: kni-infra-mdns
spec:
  volumes:
  - name: resource-dir
    hostPath:
      path: "/etc/kubernetes/static-pod-resources/mdns"
  - name: kubeconfig
    hostPath:
      path: "/etc/kubernetes/kubeconfig"
  - name: conf-dir
    hostPath:
      path: "/etc/mdns"
  initContainers:
  - name: verify-hostname
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3899b8fba1ab11d5cbff5581ca3bc7c06ba47eece58588cd53f93ead60e8ea4c
    env:
      - name: RUNTIMECFG_HOSTNAME_PATH
        value: "/etc/mdns/hostname"
    command:
    - "/bin/bash"
    - "-c"
    - |
      #!/bin/bash
      set -xv
      function get_hostname()
      {
        if [[ -s $RUNTIMECFG_HOSTNAME_PATH ]]; then
          cat $RUNTIMECFG_HOSTNAME_PATH
        else
          # if hostname wasn't updated by NM script, read hostname
          hostname
        fi
      }
      while [[ "$(get_hostname)" =~ ^localhost(.localdomain)?$ ]]; do
        echo "hostname is still set to a default value"
        sleep 1
      done
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/mdns"
  - name: render-config-mdns-publisher
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:3899b8fba1ab11d5cbff5581ca3bc7c06ba47eece58588cd53f93ead60e8ea4c
    env:
      - name: RUNTIMECFG_HOSTNAME_PATH
        value: "/etc/mdns/hostname"
    command:
    - runtimecfg
    - render
    - "/etc/kubernetes/kubeconfig"
    - "--api-vip"
    - "192.168.20.110"
    - "--ingress-vip"
    - "192.168.20.111"
    - "/config"
    - "--out-dir"
    - "/etc/mdns"
    - "--verbose"
    resources: {}
    volumeMounts:
    - name: kubeconfig
      mountPath: "/etc/kubernetes/kubeconfig"
    - name: resource-dir
      mountPath: "/config"
    - name: conf-dir
      mountPath: "/etc/mdns"
    imagePullPolicy: IfNotPresent
  containers:
  - name: mdns-publisher
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:4460e0ce7e047b86b9ad63d56cf0b953b419b47bd851b07e7ce9aa3deac64d86
    args:
    - "--debug"
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
    volumeMounts:
    - name: conf-dir
      mountPath: "/etc/mdns"
    livenessProbe:
      exec:
        command:
        - pgrep
        - mdns-publisher
      initialDelaySeconds: 10
    terminationMessagePolicy: FallbackToLogsOnError
    imagePullPolicy: IfNotPresent
  hostNetwork: true
  tolerations:
  - operator: Exists
  priorityClassName: system-node-critical
status: {}
