apiVersion: v1
baseDomain: zerotodevops.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 3
metadata:
  creationTimestamp: null
  name: demoosp
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  openstack:
    apiVIP: 10.0.0.5
    cloud: standalone
    computeFlavor: m1.large
    externalDNS: null
    externalNetwork: public
    ingressVIP: 10.0.0.7
    lbFloatingIP: 192.168.5.126
publish: External
pullSecret: <REPLACE_ME>
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCfjdWVDxtNZW5Mrb3lxfmison8iWG/diFyORcV7yKbPgzUQwk29GBbYjjR2RN5i/8Dud+SjZMGGZZtCLVO9uivHtfViC0Nu+vcTuFHgSOf/4aHxH2mYa5VYgwpAP5Ov/2lKkibM1CoF+noPdh+Gl8Izhc4ZTlNjOhG7jpVVgnd4WoK0tX5AiJ3fz3WYcDzZ4yQBNa/J43HP64l/6PX3CzgNGBVSbBHukYyzYHkIuFvSYPgnNW+dLrDx+uDypvnjYV5lYh+9jrW3lzMwiNQSzdDO30I6jupr8A05jtD5zA4maJDwUkAtcHVxc5Z2KEXlh7xWurES4amzScsHFSx3r2/NgzjD96h22BmPLN/tbZ19n21Bsb774b+vw0L471FFbsgkmiOYQcyNqcySFmeozsWixjxN2tG1VfqnH8pR189IYOX9e4YOHvYYV/5NzLjwIj2uLfGtqBOMdBGbMGyR/VeYyg9sz1nQ3mqs/sYo3OB0j+4TZeI9uJB4NZKoN4RjOc= stack@osp.home.lab
